
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/TEST_test_factory.ipynb
import operator
import torch

def test(a,b,cmp,cname=None, verbose=False):
    if cname is None: cname=cmp.__name__
    assert cmp(a, b), f'test failed: {cname}\n{a}\n{b}'
    if verbose: print(f'test passed: {cname}\n{a}\n{b}')

def test_eq(a,b, verbose=False): test(a, b,
                                      cmp=operator.eq,
                                      cname='equality',
                                      verbose=verbose)

def test_near(a, b, verbose=False, rtol=1e-3, atol=1e-5):
    if not isinstance(a, torch.Tensor): a = torch.tensor(a)
    if not isinstance(b, torch.Tensor): b = torch.tensor(b)
    test(a, b,
         cmp=lambda a,b : torch.allclose(a, b, rtol=rtol, atol=atol),
         cname='near equality',
         verbose=verbose)